// Handcrafted starter layouts for the Roomcraft demo.
//
// These are plain data, not AI output. Each layout matches the SceneLayout
// shape validated by the Roomcraft add-on: positions are object origins in
// scene-local meters, X is right, Y is up, and positive Z faces the viewer.
// Rotation is an upright Y-axis angle in radians and scale multiplies the
// catalog asset's physical size or the authored part geometry.
//
// A catalog object names an asset, while a compound object lists parts
// instead and is built from primitives at load time.

/** A warm seating group that reads well from the default preview viewpoint. */
export const READING_NOOK = {
  title: 'Reading nook',
  objects: [
    {
      id: 'nook-sofa',
      asset: 'sofa',
      name: 'Terracotta sofa',
      position: [0, 0, -1.15],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#c96f4f',
    },
    {
      id: 'nook-table',
      asset: 'coffee-table',
      name: 'Walnut coffee table',
      position: [0, 0, -0.35],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#8a5a3b',
    },
    {
      id: 'nook-chair-left',
      asset: 'armchair',
      name: 'Left reading chair',
      position: [-1.35, 0, -0.35],
      rotation: 1.15,
      scale: [1, 1, 1],
      color: '#7f8f7a',
    },
    {
      id: 'nook-chair-right',
      asset: 'armchair',
      name: 'Right reading chair',
      position: [1.35, 0, -0.35],
      rotation: -1.15,
      scale: [1, 1, 1],
      color: '#7f8f7a',
    },
    {
      id: 'nook-shelf',
      asset: 'bookshelf',
      name: 'Corner bookshelf',
      position: [-1.85, 0, -1.55],
      rotation: 0.55,
      scale: [1, 1, 1],
      color: '#5b4636',
    },
    {
      id: 'nook-lamp',
      asset: 'floor-lamp',
      name: 'Brass floor lamp',
      position: [1.65, 0, -1.5],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#e0b872',
    },
    {
      id: 'nook-plant-left',
      asset: 'plant',
      name: 'Fern by the shelf',
      position: [-1.05, 0, -1.95],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#4f7a4a',
    },
    {
      id: 'nook-plant-right',
      asset: 'plant',
      name: 'Fern by the lamp',
      position: [1.05, 0, -1.95],
      rotation: 0,
      scale: [0.85, 0.85, 0.85],
      color: '#5c8a52',
    },
    {
      id: 'nook-art-center',
      asset: 'art-panel',
      name: 'Cream canvas',
      position: [0, 0, -2.2],
      rotation: 0,
      scale: [1.2, 1, 1],
      color: '#efe3d0',
    },
    {
      id: 'nook-art-left',
      asset: 'art-panel',
      name: 'Small coral study',
      position: [-1.05, 0, -2.2],
      rotation: 0,
      scale: [0.7, 0.7, 1],
      color: '#d97757',
    },
    {
      id: 'nook-art-right',
      asset: 'art-panel',
      name: 'Small sage study',
      position: [1.05, 0, -2.2],
      rotation: 0,
      scale: [0.7, 0.7, 1],
      color: '#8fa38c',
    },
  ],
};

/** Plinths, canvases, and an entry arch, ready for an exhibit model. */
export const GALLERY = {
  title: 'Gallery walk',
  objects: [
    {
      id: 'gallery-arch',
      asset: 'arch',
      name: 'Entry arch',
      position: [0, 0, 0.75],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#e7dccb',
    },
    {
      id: 'gallery-plinth-left',
      asset: 'plinth',
      name: 'Left plinth',
      position: [-1.5, 0, -0.9],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#efe6d8',
    },
    {
      id: 'gallery-plinth-center',
      asset: 'plinth',
      name: 'Center plinth',
      position: [0, 0, -1.2],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#efe6d8',
    },
    {
      id: 'gallery-plinth-right',
      asset: 'plinth',
      name: 'Right plinth',
      position: [1.5, 0, -0.9],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#efe6d8',
    },
    {
      id: 'gallery-piece-left',
      asset: 'sphere',
      name: 'Coral sphere',
      position: [-1.5, 0.85, -0.9],
      rotation: 0,
      scale: [0.6, 0.6, 0.6],
      color: '#d97757',
    },
    {
      id: 'gallery-piece-center',
      asset: 'cone',
      name: 'Sage cone',
      position: [0, 0.85, -1.2],
      rotation: 0.4,
      scale: [0.6, 0.7, 0.6],
      color: '#7f8f7a',
    },
    {
      id: 'gallery-piece-right',
      asset: 'box',
      name: 'Slate cube',
      position: [1.5, 0.85, -0.9],
      rotation: 0.6,
      scale: [0.55, 0.55, 0.55],
      color: '#5f6672',
    },
    {
      id: 'gallery-canvas-left',
      asset: 'art-panel',
      name: 'Left canvas',
      position: [-1.7, 0, -2.35],
      rotation: 0.25,
      scale: [1, 1, 1],
      color: '#f3e9da',
    },
    {
      id: 'gallery-canvas-center',
      asset: 'art-panel',
      name: 'Center canvas',
      position: [0, 0, -2.5],
      rotation: 0,
      scale: [1.4, 1.15, 1],
      color: '#c96f4f',
    },
    {
      id: 'gallery-canvas-right',
      asset: 'art-panel',
      name: 'Right canvas',
      position: [1.7, 0, -2.35],
      rotation: -0.25,
      scale: [1, 1, 1],
      color: '#f3e9da',
    },
    {
      id: 'gallery-lamp-left',
      asset: 'floor-lamp',
      name: 'Left gallery lamp',
      position: [-2.3, 0, -1.7],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#e0b872',
    },
    {
      id: 'gallery-lamp-right',
      asset: 'floor-lamp',
      name: 'Right gallery lamp',
      position: [2.3, 0, -1.7],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#e0b872',
    },
    {
      id: 'gallery-plant',
      asset: 'plant',
      name: 'Corner planter',
      position: [-2.35, 0, -0.3],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#4f7a4a',
    },
  ],
};

/** A small block of towers, trees, and a gate, readable from above or ahead. */
export const MINIATURE_CITY = {
  title: 'Miniature city',
  objects: [
    {
      id: 'city-base',
      asset: 'box',
      name: 'City model base',
      position: [0, 0, -0.145],
      rotation: 0,
      scale: [2.4, 0.05, 1.75],
      color: '#303840',
    },
    {
      id: 'city-gate',
      asset: 'arch',
      name: 'City gate',
      position: [0, 0.025, 0.225],
      rotation: 0,
      scale: [0.225, 0.225, 0.225],
      color: '#c96f4f',
    },
    {
      id: 'city-tower-a',
      asset: 'building',
      name: 'Cream tower',
      position: [-0.3, 0.025, -0.05],
      rotation: 0,
      scale: [0.275, 0.6, 0.275],
      color: '#e6dccd',
    },
    {
      id: 'city-tower-b',
      asset: 'building',
      name: 'Slate tower',
      position: [-0.1, 0.025, -0.05],
      rotation: 0.1,
      scale: [0.25, 0.4, 0.25],
      color: '#a9b3ba',
    },
    {
      id: 'city-tower-c',
      asset: 'building',
      name: 'Coral tower',
      position: [0.1, 0.025, -0.05],
      rotation: -0.1,
      scale: [0.25, 0.5, 0.25],
      color: '#d97757',
    },
    {
      id: 'city-tower-d',
      asset: 'building',
      name: 'Sand tower',
      position: [0.3, 0.025, -0.05],
      rotation: 0,
      scale: [0.275, 0.325, 0.275],
      color: '#d8c8ac',
    },
    {
      id: 'city-tower-e',
      asset: 'building',
      name: 'Tall cream tower',
      position: [-0.3, 0.025, -0.275],
      rotation: 0,
      scale: [0.3, 0.75, 0.3],
      color: '#efe6d8',
    },
    {
      id: 'city-tower-f',
      asset: 'building',
      name: 'Sage block',
      position: [-0.1, 0.025, -0.275],
      rotation: 0.2,
      scale: [0.25, 0.3, 0.25],
      color: '#7f8f7a',
    },
    {
      id: 'city-tower-g',
      asset: 'building',
      name: 'Center spire',
      position: [0.1, 0.025, -0.275],
      rotation: 0,
      scale: [0.225, 0.9, 0.225],
      color: '#5f6672',
    },
    {
      id: 'city-tower-h',
      asset: 'building',
      name: 'Brick block',
      position: [0.3, 0.025, -0.275],
      rotation: -0.2,
      scale: [0.275, 0.45, 0.275],
      color: '#b5745a',
    },
    {
      id: 'city-tower-i',
      asset: 'building',
      name: 'Back tower',
      position: [-0.2, 0.025, -0.5],
      rotation: 0,
      scale: [0.3, 0.55, 0.3],
      color: '#c9c2b6',
    },
    {
      id: 'city-tower-j',
      asset: 'building',
      name: 'Back spire',
      position: [0.2, 0.025, -0.5],
      rotation: 0.15,
      scale: [0.25, 0.7, 0.25],
      color: '#e6dccd',
    },
    {
      id: 'city-tree-a',
      asset: 'tree',
      name: 'Street tree west',
      position: [-0.45, 0.025, -0.15],
      rotation: 0,
      scale: [0.3, 0.35, 0.3],
      color: '#4f7a4a',
    },
    {
      id: 'city-tree-b',
      asset: 'tree',
      name: 'Street tree east',
      position: [0.45, 0.025, -0.15],
      rotation: 0,
      scale: [0.3, 0.35, 0.3],
      color: '#4f7a4a',
    },
    {
      id: 'city-tree-c',
      asset: 'tree',
      name: 'Park tree',
      position: [0, 0.025, -0.1625],
      rotation: 0,
      scale: [0.25, 0.3, 0.25],
      color: '#5c8a52',
    },
    {
      id: 'city-lamp-west',
      asset: 'floor-lamp',
      name: 'Plaza light west',
      position: [-0.45, 0.025, 0.075],
      rotation: 0,
      scale: [0.15, 0.2, 0.15],
      color: '#e0b872',
    },
    {
      id: 'city-lamp-east',
      asset: 'floor-lamp',
      name: 'Plaza light east',
      position: [0.45, 0.025, 0.075],
      rotation: 0,
      scale: [0.15, 0.2, 0.15],
      color: '#e0b872',
    },
  ],
};

/**
 * One handcrafted compound object, written by hand to show what a grouped
 * design looks like. Gemini did not produce it, and it is not a catalog asset:
 * the parts below are ordinary primitives that any live design also uses.
 * Part positions are centers in parent-local meters, sizes are physical
 * meters, and a parent's size never scales its children. The feet rest at
 * y = 0 so the object stands on the scene floor.
 */
export const ROBOT_EXAMPLE = {
  title: 'Robot example',
  objects: [
    {
      id: 'example-robot',
      name: 'Handcrafted robot',
      position: [0, 0, -0.6],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#ffffff',
      parts: [
        {
          id: 'torso',
          name: 'Torso',
          shape: 'box',
          parent: null,
          position: [0, 0.4, 0],
          rotation: [0, 0, 0],
          size: [0.3, 0.32, 0.2],
          color: '#8fa3b0',
        },
        {
          id: 'chest-panel',
          name: 'Chest panel',
          shape: 'box',
          parent: 'torso',
          position: [0, 0.02, 0.105],
          rotation: [0, 0, 0],
          size: [0.14, 0.12, 0.02],
          color: '#e8714a',
        },
        {
          id: 'neck',
          name: 'Neck',
          shape: 'cylinder',
          parent: 'torso',
          position: [0, 0.185, 0],
          rotation: [0, 0, 0],
          size: [0.07, 0.05, 0.07],
          color: '#5f6672',
        },
        {
          id: 'head',
          name: 'Head',
          shape: 'box',
          parent: 'torso',
          position: [0, 0.31, 0],
          rotation: [0, 0, 0],
          size: [0.22, 0.2, 0.2],
          color: '#c9c2b6',
        },
        {
          id: 'eye-left',
          name: 'Left eye',
          shape: 'sphere',
          parent: 'head',
          position: [-0.055, 0.02, 0.1],
          rotation: [0, 0, 0],
          size: [0.05, 0.05, 0.03],
          color: '#2b2f36',
        },
        {
          id: 'eye-right',
          name: 'Right eye',
          shape: 'sphere',
          parent: 'head',
          position: [0.055, 0.02, 0.1],
          rotation: [0, 0, 0],
          size: [0.05, 0.05, 0.03],
          color: '#2b2f36',
        },
        {
          id: 'antenna',
          name: 'Antenna',
          shape: 'cylinder',
          parent: 'head',
          position: [0, 0.145, 0],
          rotation: [0, 0, 0],
          size: [0.015, 0.09, 0.015],
          color: '#5f6672',
        },
        {
          id: 'antenna-tip',
          name: 'Antenna tip',
          shape: 'sphere',
          parent: 'antenna',
          position: [0, 0.06, 0],
          rotation: [0, 0, 0],
          size: [0.04, 0.04, 0.04],
          color: '#e8714a',
        },
        {
          id: 'arm-left',
          name: 'Left arm',
          shape: 'capsule',
          parent: 'torso',
          position: [-0.195, 0.02, 0],
          rotation: [0, 0, 0],
          size: [0.07, 0.26, 0.07],
          color: '#7f8f7a',
        },
        {
          id: 'arm-right',
          name: 'Right arm',
          shape: 'capsule',
          parent: 'torso',
          position: [0.195, 0.02, 0],
          rotation: [0, 0, 0],
          size: [0.07, 0.26, 0.07],
          color: '#7f8f7a',
        },
        {
          id: 'hand-left',
          name: 'Left hand',
          shape: 'sphere',
          parent: 'arm-left',
          position: [0, -0.15, 0],
          rotation: [0, 0, 0],
          size: [0.075, 0.075, 0.075],
          color: '#e0b872',
        },
        {
          id: 'hand-right',
          name: 'Right hand',
          shape: 'sphere',
          parent: 'arm-right',
          position: [0, -0.15, 0],
          rotation: [0, 0, 0],
          size: [0.075, 0.075, 0.075],
          color: '#e0b872',
        },
        {
          id: 'leg-left',
          name: 'Left leg',
          shape: 'cylinder',
          parent: 'torso',
          position: [-0.085, -0.25, 0],
          rotation: [0, 0, 0],
          size: [0.09, 0.18, 0.09],
          color: '#5f6672',
        },
        {
          id: 'leg-right',
          name: 'Right leg',
          shape: 'cylinder',
          parent: 'torso',
          position: [0.085, -0.25, 0],
          rotation: [0, 0, 0],
          size: [0.09, 0.18, 0.09],
          color: '#5f6672',
        },
        {
          id: 'foot-left',
          name: 'Left foot',
          shape: 'box',
          parent: 'leg-left',
          position: [0, -0.12, 0.03],
          rotation: [0, 0, 0],
          size: [0.11, 0.06, 0.18],
          color: '#3f454d',
        },
        {
          id: 'foot-right',
          name: 'Right foot',
          shape: 'box',
          parent: 'leg-right',
          position: [0, -0.12, 0.03],
          rotation: [0, 0, 0],
          size: [0.11, 0.06, 0.18],
          color: '#3f454d',
        },
      ],
    },
  ],
};

/** The starter scenes offered in the demo, in the order they are shown. */
export const STARTER_SCENES = [
  {
    id: 'reading-nook',
    label: 'Reading nook',
    summary: 'A sofa, two chairs, a shelf, and framed art.',
    layout: READING_NOOK,
  },
  {
    id: 'gallery',
    label: 'Gallery',
    summary: 'Plinths, canvases, and an entry arch.',
    layout: GALLERY,
  },
  {
    id: 'miniature-city',
    label: 'Miniature city',
    summary: 'A block of towers, trees, and a gate.',
    layout: MINIATURE_CITY,
  },
  {
    id: 'robot-example',
    label: 'Robot example',
    summary:
      'One handcrafted compound object made of 16 primitive parts, not AI output.',
    layout: ROBOT_EXAMPLE,
  },
];
