// Handcrafted starter layouts for the Roomcraft demo.
//
// These are plain data, not AI output. Each layout matches the SceneLayout
// shape validated by the Roomcraft add-on: positions are object bases in
// scene-local meters, X is right, Y is up, and positive Z faces the viewer.
// Rotation is an upright Y-axis angle in radians and scale multiplies the
// catalog asset's physical size.

/** A warm seating group that reads well from the default preview viewpoint. */
export const READING_NOOK = {
  title: 'Reading nook',
  objects: [
    {
      id: 'nook-sofa',
      asset: 'sofa',
      name: 'Terracotta sofa',
      position: [0, 0, -1.15],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#c96f4f',
    },
    {
      id: 'nook-table',
      asset: 'coffee-table',
      name: 'Walnut coffee table',
      position: [0, 0, -0.35],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#8a5a3b',
    },
    {
      id: 'nook-chair-left',
      asset: 'armchair',
      name: 'Left reading chair',
      position: [-1.35, 0, -0.35],
      rotation: 1.15,
      scale: [1, 1, 1],
      color: '#7f8f7a',
    },
    {
      id: 'nook-chair-right',
      asset: 'armchair',
      name: 'Right reading chair',
      position: [1.35, 0, -0.35],
      rotation: -1.15,
      scale: [1, 1, 1],
      color: '#7f8f7a',
    },
    {
      id: 'nook-shelf',
      asset: 'bookshelf',
      name: 'Corner bookshelf',
      position: [-1.85, 0, -1.55],
      rotation: 0.55,
      scale: [1, 1, 1],
      color: '#5b4636',
    },
    {
      id: 'nook-lamp',
      asset: 'floor-lamp',
      name: 'Brass floor lamp',
      position: [1.65, 0, -1.5],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#e0b872',
    },
    {
      id: 'nook-plant-left',
      asset: 'plant',
      name: 'Fern by the shelf',
      position: [-1.05, 0, -1.95],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#4f7a4a',
    },
    {
      id: 'nook-plant-right',
      asset: 'plant',
      name: 'Fern by the lamp',
      position: [1.05, 0, -1.95],
      rotation: 0,
      scale: [0.85, 0.85, 0.85],
      color: '#5c8a52',
    },
    {
      id: 'nook-art-center',
      asset: 'art-panel',
      name: 'Cream canvas',
      position: [0, 0, -2.2],
      rotation: 0,
      scale: [1.2, 1, 1],
      color: '#efe3d0',
    },
    {
      id: 'nook-art-left',
      asset: 'art-panel',
      name: 'Small coral study',
      position: [-1.05, 0, -2.2],
      rotation: 0,
      scale: [0.7, 0.7, 1],
      color: '#d97757',
    },
    {
      id: 'nook-art-right',
      asset: 'art-panel',
      name: 'Small sage study',
      position: [1.05, 0, -2.2],
      rotation: 0,
      scale: [0.7, 0.7, 1],
      color: '#8fa38c',
    },
  ],
};

/** Plinths, canvases, and an entry arch, ready for an exhibit model. */
export const GALLERY = {
  title: 'Gallery walk',
  objects: [
    {
      id: 'gallery-arch',
      asset: 'arch',
      name: 'Entry arch',
      position: [0, 0, 0.75],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#e7dccb',
    },
    {
      id: 'gallery-plinth-left',
      asset: 'plinth',
      name: 'Left plinth',
      position: [-1.5, 0, -0.9],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#efe6d8',
    },
    {
      id: 'gallery-plinth-center',
      asset: 'plinth',
      name: 'Center plinth',
      position: [0, 0, -1.2],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#efe6d8',
    },
    {
      id: 'gallery-plinth-right',
      asset: 'plinth',
      name: 'Right plinth',
      position: [1.5, 0, -0.9],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#efe6d8',
    },
    {
      id: 'gallery-piece-left',
      asset: 'sphere',
      name: 'Coral sphere',
      position: [-1.5, 0.85, -0.9],
      rotation: 0,
      scale: [0.6, 0.6, 0.6],
      color: '#d97757',
    },
    {
      id: 'gallery-piece-center',
      asset: 'cone',
      name: 'Sage cone',
      position: [0, 0.85, -1.2],
      rotation: 0.4,
      scale: [0.6, 0.7, 0.6],
      color: '#7f8f7a',
    },
    {
      id: 'gallery-piece-right',
      asset: 'box',
      name: 'Slate cube',
      position: [1.5, 0.85, -0.9],
      rotation: 0.6,
      scale: [0.55, 0.55, 0.55],
      color: '#5f6672',
    },
    {
      id: 'gallery-canvas-left',
      asset: 'art-panel',
      name: 'Left canvas',
      position: [-1.7, 0, -2.35],
      rotation: 0.25,
      scale: [1, 1, 1],
      color: '#f3e9da',
    },
    {
      id: 'gallery-canvas-center',
      asset: 'art-panel',
      name: 'Center canvas',
      position: [0, 0, -2.5],
      rotation: 0,
      scale: [1.4, 1.15, 1],
      color: '#c96f4f',
    },
    {
      id: 'gallery-canvas-right',
      asset: 'art-panel',
      name: 'Right canvas',
      position: [1.7, 0, -2.35],
      rotation: -0.25,
      scale: [1, 1, 1],
      color: '#f3e9da',
    },
    {
      id: 'gallery-lamp-left',
      asset: 'floor-lamp',
      name: 'Left gallery lamp',
      position: [-2.3, 0, -1.7],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#e0b872',
    },
    {
      id: 'gallery-lamp-right',
      asset: 'floor-lamp',
      name: 'Right gallery lamp',
      position: [2.3, 0, -1.7],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#e0b872',
    },
    {
      id: 'gallery-plant',
      asset: 'plant',
      name: 'Corner planter',
      position: [-2.35, 0, -0.3],
      rotation: 0,
      scale: [1, 1, 1],
      color: '#4f7a4a',
    },
  ],
};

/** A small block of towers, trees, and a gate, readable from above or ahead. */
export const MINIATURE_CITY = {
  title: 'Miniature city',
  objects: [
    {
      id: 'city-base',
      asset: 'box',
      name: 'City model base',
      position: [0, 0, -0.145],
      rotation: 0,
      scale: [2.4, 0.05, 1.75],
      color: '#303840',
    },
    {
      id: 'city-gate',
      asset: 'arch',
      name: 'City gate',
      position: [0, 0.025, 0.225],
      rotation: 0,
      scale: [0.225, 0.225, 0.225],
      color: '#c96f4f',
    },
    {
      id: 'city-tower-a',
      asset: 'building',
      name: 'Cream tower',
      position: [-0.3, 0.025, -0.05],
      rotation: 0,
      scale: [0.275, 0.6, 0.275],
      color: '#e6dccd',
    },
    {
      id: 'city-tower-b',
      asset: 'building',
      name: 'Slate tower',
      position: [-0.1, 0.025, -0.05],
      rotation: 0.1,
      scale: [0.25, 0.4, 0.25],
      color: '#a9b3ba',
    },
    {
      id: 'city-tower-c',
      asset: 'building',
      name: 'Coral tower',
      position: [0.1, 0.025, -0.05],
      rotation: -0.1,
      scale: [0.25, 0.5, 0.25],
      color: '#d97757',
    },
    {
      id: 'city-tower-d',
      asset: 'building',
      name: 'Sand tower',
      position: [0.3, 0.025, -0.05],
      rotation: 0,
      scale: [0.275, 0.325, 0.275],
      color: '#d8c8ac',
    },
    {
      id: 'city-tower-e',
      asset: 'building',
      name: 'Tall cream tower',
      position: [-0.3, 0.025, -0.275],
      rotation: 0,
      scale: [0.3, 0.75, 0.3],
      color: '#efe6d8',
    },
    {
      id: 'city-tower-f',
      asset: 'building',
      name: 'Sage block',
      position: [-0.1, 0.025, -0.275],
      rotation: 0.2,
      scale: [0.25, 0.3, 0.25],
      color: '#7f8f7a',
    },
    {
      id: 'city-tower-g',
      asset: 'building',
      name: 'Center spire',
      position: [0.1, 0.025, -0.275],
      rotation: 0,
      scale: [0.225, 0.9, 0.225],
      color: '#5f6672',
    },
    {
      id: 'city-tower-h',
      asset: 'building',
      name: 'Brick block',
      position: [0.3, 0.025, -0.275],
      rotation: -0.2,
      scale: [0.275, 0.45, 0.275],
      color: '#b5745a',
    },
    {
      id: 'city-tower-i',
      asset: 'building',
      name: 'Back tower',
      position: [-0.2, 0.025, -0.5],
      rotation: 0,
      scale: [0.3, 0.55, 0.3],
      color: '#c9c2b6',
    },
    {
      id: 'city-tower-j',
      asset: 'building',
      name: 'Back spire',
      position: [0.2, 0.025, -0.5],
      rotation: 0.15,
      scale: [0.25, 0.7, 0.25],
      color: '#e6dccd',
    },
    {
      id: 'city-tree-a',
      asset: 'tree',
      name: 'Street tree west',
      position: [-0.45, 0.025, -0.15],
      rotation: 0,
      scale: [0.3, 0.35, 0.3],
      color: '#4f7a4a',
    },
    {
      id: 'city-tree-b',
      asset: 'tree',
      name: 'Street tree east',
      position: [0.45, 0.025, -0.15],
      rotation: 0,
      scale: [0.3, 0.35, 0.3],
      color: '#4f7a4a',
    },
    {
      id: 'city-tree-c',
      asset: 'tree',
      name: 'Park tree',
      position: [0, 0.025, -0.1625],
      rotation: 0,
      scale: [0.25, 0.3, 0.25],
      color: '#5c8a52',
    },
    {
      id: 'city-lamp-west',
      asset: 'floor-lamp',
      name: 'Plaza light west',
      position: [-0.45, 0.025, 0.075],
      rotation: 0,
      scale: [0.15, 0.2, 0.15],
      color: '#e0b872',
    },
    {
      id: 'city-lamp-east',
      asset: 'floor-lamp',
      name: 'Plaza light east',
      position: [0.45, 0.025, 0.075],
      rotation: 0,
      scale: [0.15, 0.2, 0.15],
      color: '#e0b872',
    },
  ],
};

/** The starter scenes offered in the demo, in the order they are shown. */
export const STARTER_SCENES = [
  {
    id: 'reading-nook',
    label: 'Reading nook',
    summary: 'A sofa, two chairs, a shelf, and framed art.',
    layout: READING_NOOK,
  },
  {
    id: 'gallery',
    label: 'Gallery',
    summary: 'Plinths, canvases, and an entry arch.',
    layout: GALLERY,
  },
  {
    id: 'miniature-city',
    label: 'Miniature city',
    summary: 'A block of towers, trees, and a gate.',
    layout: MINIATURE_CITY,
  },
];
